name: Site Update

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
      with:
        repository: sameboy/sameboy.github.io
        token: ${{ secrets.WEBSITETOKEN }}
        submodules: false
    
    - run: git config --global user.name 'Automation Updater' && git config --global user.email '<>' && git rm automation && git submodule add https://github.com/LIJI32/SameBoyAutomation.git automation && git add automation && git commit -m 'Update automation submodule' && git push
